#pragma once

#include <plugin.hpp>

#define PLUGIN_BUILD 0
#define PLUGIN_DESC L"Hello Plugin for Far Manager x64"
#define PLUGIN_NAME L"HelloFar"
#define PLUGIN_FILENAME L"HelloFar.dll"
#define PLUGIN_AUTHOR L"CodePicker13"
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
